---
- name: Descargar paquete RPM de Kibana
  ansible.builtin.get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-9.3.3-x86_64.rpm"
    dest: /tmp/kibana.rpm
    mode: '0644'

- name: Instalar Kibana desde RPM
  ansible.builtin.dnf:
    name: /tmp/kibana.rpm
    state: present
    disable_gpg_check: yes

- name: Configurar Kibana para usar Elasticsearch local
  ansible.builtin.blockinfile:
    path: /etc/kibana/kibana.yml
    block: |
      server.host: "127.0.0.1"
      server.port: 5601
      elasticsearch.hosts: ["http://127.0.0.1:9200"]

- name: Recargar systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Habilitar y arrancar Kibana
  ansible.builtin.service:
    name: kibana
    enabled: yes
    state: started