---
- name: Descargar paquete de Elasticsearch
  ansible.builtin.get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.3.3-x86_64.rpm"
    dest: /tmp/elasticsearch.rpm
    mode: '0644'

- name: Limpiar caché DNF
  ansible.builtin.command: dnf clean all

- name: Instalar Elasticsearch desde RPM
  ansible.builtin.dnf:
    name: /tmp/elasticsearch.rpm
    state: present
    disable_gpg_check: yes

- name: Configurar Elasticsearch (single node y localhost)
  ansible.builtin.blockinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    block: |
      network.host: 127.0.0.1
      discovery.type: single-node

- name: Recargar systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: Habilitar y arrancar Elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    enabled: yes
    state: started
  when: ansible_service_mgr == "systemd"

